name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          # Linux and MacOS
          start: yarn start
          # Takes precedences on Windows
          start-windows: npm run start:windows:server
          wait-on: 'http://127.0.0.1:8000'
          # wait for 2 minutes for the server to respond
          wait-on-timeout: 120
          spec: cypress/integration/home-page.js
